### ISSUE TITLE
NullPointerException in gov.nist.javax.sip.message.SipMessage.encodeAsBytes() method's if topVia variable is null.

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/sip-servlets#102]
I have an envrionment where a jboss application server uses mobicent sip-servlets (which uses jain-sip) to send sip messages to other endpoints.

I have run some failover tests in this environment: I have blocked the network address of these endpoints using IPTABLES DROP rules on the host machine. Unfortunatelly there were some NullPointerExceptions in the app. server's log:

    java.lang.NullPointerException
    at gov.nist.javax.sip.message.SIPMessage.encodeAsBytes(SIPMessage.java:497)
    at gov.nist.javax.sip.message.SIPRequest.encodeAsBytes(SIPRequest.java:620)
    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.cleanUp(SIPClientTransactionImpl.java:1842)
    at  gov.nist.javax.sip.stack.SIPClientTransactionImpl.cleanUpOnTerminated(SIPClientTransactionImpl.jav    a:1927)
    at gov.nist.javax.sip.stack.SIPClientTransactionImpl$TransactionTimer.runTask(SIPClientTransactionImpl.java:253)
    at gov.nist.javax.sip.stack.timers.DefaultSipTimer$DefaultTimerTask.run(DefaultSipTimer.java:63)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)

The exception is thrown because the topVia parameter is null in SIPMessage.java:497:

    ViaHeader topVia = (ViaHeader) this.getHeader(ViaHeader.NAME);
    try {
          topVia.setTransport(transport);
    } catch (ParseException e) {
          InternalErrorHandler.handleException(e);
    }

After doing some quick debug, it turned out that the VIA header is removed from the message by org.mobicents.servlet.sip.message.SipServletRequestImpl.send() method's line 1375:
```
} catch (Exception ex) {	
...
    request.removeFirst(ViaHeader.NAME);
...
}
```

I could fix this easily with a topVia header null check in SIPMessage, but I am not sure whether this simple fix would add some unwanted side effects or not. What is your opinion?

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/102/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
If I understand correctly, you running DNS failover tests right ? So in that case the sipservletrequest remove the via header before it checks for sending to the next hop, correct ?

I realize that we clone the request after, which is probably a wrong thing to do in that case. Can you check if moving this line https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1377 before https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1374 would fix the issue in your environment and attach logs if not ?

**Comment by AlerantAppNGIN** [comment]
I've modified SipServletRequest.java as suggested, but unfortunatelly the issue still exists. I've attached the log file (I've turned on TRACE level logging for org.mobicents.servlet.sip classes):
[slessEL01a.zip](https://github.com/RestComm/sip-servlets/files/104939/slessEL01a.zip)

In this scenario the application server sends OPTIONS messages periodically to the endpoints, first NPE occured at 2016-01-26 14:17:13,395, sortly after we've blocked all endpoint addresses via an iptables rule.

**Comment by AlerantAppNGIN** [comment]
Now, I beleive I have a better understanding of the situation:

- this terminateTransaction() call https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1364 terminates the SIP transaction, in my case it calls this https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/stack/SIPClientTransactionImpl.java#L1448 terminate() method which sets its state to _TERMINATED. 

- there is also a timer thread defined in this class (https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/stack/SIPClientTransactionImpl.java#L234) which check's this state in every baseTimerInterval period (it defined here: https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/stack/SIPClientTransactionImpl.java#L1429). If the state becomes _TERMINATED, then it cleans up the transaction by calling the cleanUpOnTerminated() method which calls cleanUp() and gov.nist.javax.sip.message.SIPMessage.encodeAsBytes().

- if the VIA header remove code line (https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1374) is executed before the timer thread reaches encodeAsBytes() the NPE issue will happen.

My only idea so far to fix this is to suspend the thread executing SIPClientTransactionImpl after the tx termination, in order to prevent reaching the VIA header removal code, till the timer thread finishes its encoding job on the SIPMessage. For example with something like this:

```
JainSipUtils.terminateTransaction(tx);
// wait till SIPClientTransactionImpl's. TransactionTimer cleans up after tx.terminateTransaction():
if(tx instanceof SIPClientTransaction){
    try{
        Thread.sleep(2*((SIPClientTransaction)tx).getBaseTimerInterval());
    }catch(Throwable t){
        logger.warn("Exception during baseTimerInterval sleep:",t); 
    }
}
		
// cleaning up the request to make sure it can be resent with some modifications in case of exception
if(transactionApplicationData.getHops() != null && transactionApplicationData.getHops().size() > 0) {
	request.removeFirst(RouteHeader.NAME);
	// https://code.google.com/p/sipservlets/issues/detail?id=250 retry directly on TCP
        boolean nextHopVisited = visitNextHop();
        if(nextHopVisited) {
            	return;
         }
}

request.removeFirst(ViaHeader.NAME);
request.removeFirst(ContactHeader.NAME);
setTransaction(null);
message = (Request) request.clone();
```

**Comment by deruelle** [comment]
Something is fishy here as if you clone the request as discussed before this shouldn't happen as it won't be the same object so there would be no NPE

When you moved this line https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1377 before https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1374 

did you also remove the Via Haeder on the cloned request ie https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java#L1374 would become message.removeFirst(ViaHeader.NAME); ?

I don't like the sleep type of hacks it's not good, we need a cleaner solution

**Comment by AlerantAppNGIN** [comment]
So you suggest to try this, right?
    message = (Request) request.clone();

    message.removeFirst(ViaHeader.NAME);
    message.removeFirst(ContactHeader.NAME);
    
    setTransaction(null);

Let me check this, I will come back with the result soon.

**Comment by AlerantAppNGIN** [comment]
I've just tested this, it's ok now. Thanks for the help, I will open a pull request for this fix if it is ok for you.

**Comment by deruelle** [comment]
Great. Sure, thanks for making a pull request.
