### ISSUE TITLE
Removing UndertowSipConnectorActivateProcessor/Service from wildfly8

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/sip-servlets#115]
SipConnectorActivateService only starts sip connector when all deployments are ready. However sip servlets can start sending sip messages after the servlet initialized, but before deployments marked ready by wildfly container. 

To fulfill sip servlet spec, we need to remove SipConnectorActivateService in order to provide initialized sip servlets to send sip messages.

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/115/create?referer=github" target="_blank">Log Time</a>

**Comment by deruelle** [comment]
I'm not sure I fully understand the issue here. Please note that the SIPServlet Application is only allowed to send messages when the container has called servletInitialized callback from ServletListener, not before. So I'm wondering if removing that service will make us spec uncompliant ?

**Comment by AlerantAppNGIN** [comment]
Hi Jean!

The problem is that we are not able to send messages after the container has called servletInitialized callback from ServletListener, but before the deployment processor has finished the deployments.

Because the service does not allow the sip connector to become active before the deployments are ready.

Regards,
Istvan

**Comment by deruelle** [comment]
Actually the servletInitialized shouldn't be called then until the SIP connectors are ready, in that case. Can you provide a diagram of the issue you're having just to make sure I get it correctly ?

**Comment by deruelle** [comment]
AS8 will not be supported, only AS 10 will be so we can close this one
