### ISSUE TITLE
Address.equals fails when q values are 1 vs 1.0

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#123]
I am doing client side sip REGISTER, and trying to get my assigned expires from binding in the REGISTER response. To achieve this I am taking the contact address from the register request, and comparing it to each of the contact bindings int the REGISTER response. This comparison is failing to find my binding because the q value parameter of the request is "1", and the q value parameter of my binding in the response is "1.0". If I modify the q values to be both "1.0" the comparison succeeds and I can retrieve my binding's expires.

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/123/create?referer=github" target="_blank">Log Time</a>

**Comment by xhoaluu** [comment]
Closed
