### ISSUE TITLE
SipServletMessage.addHeader handles transport badly

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#15]
See https://code.google.com/p/sipservlets/issues/detail?id=268

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/15/create?referer=github" target="_blank">Log Time</a>

**Comment by xhoaluu** [comment]
In the time I'm waiting for external review for #110, Could I take this one to work? I have successfully reproduce this issue.

**Comment by deruelle** [comment]
@xhoaluu sure go ahead :D

**Comment by xhoaluu** [comment]
Closed
