### ISSUE TITLE
Often SipServlets on JBoss AS7 starts with SIP outbound interfaces null

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/sip-servlets#165]
the issue will happen more often if you run Restcomm on a fast machine

To reproduce you can download Restcomm start it, 50% of the times you will get the issue

Problem is :

[11:38]  
09:29:03,884 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager](RestComm-akka.actor.default-dispatcher-6) SipURI outboundIntf is null
09:29:03,885 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager](RestComm-akka.actor.default-dispatcher-6) SipURI outboundIntf is null.

this is a SipServlet on the servletInitialized method. Its the entry point that we use to initialise Akka

Code is calling
final List<SipURI> uris = (List<SipURI>) servletConfig.getServletContext().getAttribute(OUTBOUND_INTERFACES);

**Comment by atsakiridis** [comment]
Here are some additional logs right before, just in case they are needed:

```
09:29:01,857 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-16) JBAS015893: Encountered invalid class name 'com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$Text' for service type 'javax.ws.rs.ext.MessageBodyWriter'
09:29:01,857 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-16) JBAS015893: Encountered invalid class name 'com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General' for service type 'javax.ws.rs.ext.MessageBodyWriter'
09:29:01,858 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-16) JBAS015893: Encountered invalid class name 'com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter' for service type 'javax.ws.rs.ext.MessageBodyWriter'
09:29:01,859 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-16) JBAS015893: Encountered invalid class name 'org.xmlpull.mxp1.MXParser,org.xmlpull.mxp1_serializer.MXSerializer' for service type 'org.xmlpull.v1.XmlPullParserFactory'
09:29:02,135 WARN  [org.jboss.weld.deployer] (MSC service thread 1-10) JBAS016012: Deployment deployment "restcomm.war" contains CDI annotations but beans.xml was not found.
09:29:02,187 WARN  [com.vendor.dialogic.javax.media.mscontrol.spi.DlgcDriver] (ServerService Thread Pool -- 58) Configuration File: DLG_PROPERTY_FILE not provided
09:29:03,182 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-5) Failed to locate properties file, using default values
09:29:03,866 WARN  [org.mobicents.servlet.restcomm.Version] (ServerService Thread Pool -- 58) Unable to extract the version of Mobicents Restcomm currently running
09:29:03,867 ERROR [org.mobicents.servlet.sip.startup.SipStandardContext] (ServerService Thread Pool -- 58) An error occured when notifying the servlet org.mobicents.servlet.restcomm.Bootstrapper of the event SERVLET_INITIALIZED: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.Bootstrapper.servletInitialized(Bootstrapper.java:365)
	at org.mobicents.servlet.sip.startup.SipStandardContext.notifySipContextListeners(SipStandardContext.java:1330) [sip-servlets-as7-7.0.4.394.jar:7.0.4.394]
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.addSipApplication(SipApplicationDispatcherImpl.java:594) [sip-servlets-impl-7.0.4.394.jar:7.0.4.394]
	at org.mobicents.servlet.sip.startup.SipStandardContext.start(SipStandardContext.java:380) [sip-servlets-as7-7.0.4.394.jar:7.0.4.394]
	at org.mobicents.as7.deployment.SIPWebContext.start(SIPWebContext.java:141)
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156)
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60)
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_95]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_95]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
09:29:03,884 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-6) SipURI outboundIntf is null
09:29:03,885 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-6) SipURI outboundIntf is null

```

**Comment by jaimecasero** [comment]
it maybe the variable holding the servletcontext needs to be set as volatile

**Comment by jaimecasero** [comment]
With a local app accesing the atttribute from container thread i was unable to reproduce. 10 times in a row it worked
18:19:39,449 INFO  [class com.avaya.proxy.ProxySipServlet] (ServerService Thread Pool -- 55) Outbound uris:[sip:192.168.1.17:5082;transport=ws, sip:127.0.0.1:5082;transport=ws, sip:192.168.1.17:5083;transport=wss, sip:127.0.0.1:5083;transport=wss, sip:192.168.1.17:5081;transport=tls, sip:127.0.0.1:5081;transport=tls, sip:192.168.1.17:5080;transport=tcp, sip:127.0.0.1:5080;transport=tcp, sip:192.168.1.17:5080;transport=udp, sip:127.0.0.1:5080;transport=udp]

**Comment by jaimecasero** [comment]
Tried with app that creates a new thread to do the var lookup
18:21:27,828 INFO  [class com.avaya.proxy.ProxySipServlet] (Thread-112) Outbound uris:[sip:192.168.1.17:5083;transport=wss, sip:127.0.0.1:5083;transport=wss, sip:192.168.1.17:5081;transport=tls, sip:127.0.0.1:5081;transport=tls, sip:192.168.1.17:5080;transport=tcp, sip:127.0.0.1:5080;transport=tcp, sip:192.168.1.17:5082;transport=ws, sip:127.0.0.1:5082;transport=ws, sip:192.168.1.17:5080;transport=udp, sip:127.0.0.1:5080;transport=udp]


not reproduced, it maybe Restcomm related, lets use restcomm instead

**Comment by jaimecasero** [comment]
not reproduced using Restcomm-JBoss-AS7-7.8.0.941 build

**Comment by gvagenas** [comment]
@jaimecasero using latest Restcomm in my machine the issue is reproducable 50% of the times I start Restcomm. I am using wlan0 interface but the same issue happens when using eth0 on a server (at EC2 for example). 
Next time it happens I will collect configuration files (SipServlets and Restcomm) and logs and will attach them here.

**Comment by jaimecasero** [comment]
Apparently its not happening in my env Centos 6.6 over virtaul box

It happens in George env EC2 based

**Comment by jaimecasero** [comment]
finally make it happen
09:24:01,044 ERROR [org.mobicents.servlet.sip.startup.SipStandardContext] (ServerService Thread Pool -- 56) An error occured when notifying the servlet org.mobicents.servlet.restcomm.Bootstrapper of the event SERVLET_INITIALIZED: java.lang.NullPointerException
        at org.mobicents.servlet.restcomm.Bootstrapper.servletInitialized(Bootstrapper.java:365)

**Comment by jaimecasero** [comment]
Seems init logic is called concurrently:
`
10:43:07,677 DEBUG [org.mobicents.servlet.sip.catalina.SipProtocolHandler] (MSC service thread 1-4) Adding hostname for IP load balancer 192.168.1.17:5082
10:43:07,677 DEBUG [org.mobicents.servlet.sip.catalina.SipProtocolHandler] (MSC service thread 1-4) Adding the Sip Application Dispatcher as a sip listener for connector listening on port 5082
10:43:07,677 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-4) Outbound Interface List :
10:43:07,678 DEBUG [org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl] (MSC service thread 1-8) org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl@21256c5a
10:43:07,678 DEBUG [org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl] (MSC service thread 1-8) Adding hostname 192.168.1.17:5083
10:43:07,678 DEBUG [org.mobicents.ext.javax.sip.dns.DefaultDNSServerLocator] (MSC service thread 1-8) Adding localHostName 192.168.1.17:5083
10:43:07,678 DEBUG [org.mobicents.servlet.sip.catalina.SipProtocolHandler] (MSC service thread 1-8) Adding hostname for IP load balancer 192.168.1.17:5083
10:43:07,678 DEBUG [org.mobicents.servlet.sip.catalina.SipProtocolHandler] (MSC service thread 1-8) Adding the Sip Application Dispatcher as a sip listener for connector listening on port 5083
10:43:07,678 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-8) Outbound Interface List :
10:43:07,702 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-4) Outbound Interface : sip:192.168.1.17:5082;transport=ws
10:43:07,702 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-8) Outbound Interface : sip:192.168.1.17:5082;transport=ws

`

**Comment by jaimecasero** [comment]
[outgood.zip](https://github.com/RestComm/sip-servlets/files/318682/outgood.zip)
Here we can see a positive scenario. 
We can see how outbound List is updated everytime a new listening point is added. Those happens on MSC threads
`
10:42:28,386 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-4) Outbound Interface List : 
10:42:28,386 DEBUG [org.mobicents.servlet.sip.core.SipNetworkInterfaceManagerImpl] (MSC service thread 1-4) Outbound Interface : sip:192.168.1.17:5083;transport=wss
`
Later we can see Restcomm Bootstrapper finding the intfs:
`
10:42:22,455 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 57) Outbound interface found: sip:192.168.1.17:5080;transport=udp
 `

**Comment by jaimecasero** [comment]
Apparently the faster the machine the more probability to get the failure

**Comment by jaimecasero** [comment]
![outbreakpoint](https://cloud.githubusercontent.com/assets/7847241/16122870/202abd3e-33e9-11e6-8811-585d13fbe76f.jpg)
Set a breakpoint on both outboundInt calculation and Restcomm init. Both were hit, proving depending on thread scheduling the Restcomm init code maybe run before the listeningPoints are added. This is quite unexpected from App logic perspective. I bet JEE specifications details this behaviour

**Comment by jaimecasero** [comment]
It seems Jboss subssystems are started in parallel
https://developer.jboss.org/message/776404#776404
https://developer.jboss.org/thread/228854?tstart=0

**Comment by jaimecasero** [comment]
Implemented an active wait for the SipStandardService to be started before creating any sip context. This way servletInitialized is not called until whole sip stack is ready...

**Comment by jaimecasero** [comment]
calling prepareContext again when sipappsipatcher invoked the ServletInitilized event made the trick...

**Comment by jaimecasero** [comment]
Apparently it happened again. Specially when TLS connector is setup...

**Comment by jaimecasero** [comment]
attempted 20 times with Restcomm-JBoss-AS7-7.8.0.959 . not reproduced

**Comment by jaimecasero** [comment]
Agreed to add more traces so we may extract info next ti happens...

**Comment by jaimecasero** [comment]
[error_startingtelestaxRC.zip](https://github.com/RestComm/sip-servlets/files/459031/error_startingtelestaxRC.zip)

lastest occurrence....

**Comment by jaimecasero** [comment]
Using EC2 c3.2xlarge instance  with Restcomm-JBoss-AS7-7.9.0.1006 build
no sign of issue again
`
13:04:08,979 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:05:43,551 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 58) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:07:36,765 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 52) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:07:53,435 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 57) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:08:11,773 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 51) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:08:25,084 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 58) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:39:37,816 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 52) Outbound interface found: sip:127.0.0.1:5080;transport=udp
13:54:27,133 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:21:10,296 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 57) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:21:32,546 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:23:10,648 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 56) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:24:22,149 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 58) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:26:18,958 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 56) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:27:15,905 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 56) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:27:32,480 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:27:48,098 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 58) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:28:03,124 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 52) Outbound interface found: sip:127.0.0.1:5080;transport=udp
14:29:00,684 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 58) Outbound interface found: sip:127.0.0.1:5080;transport=udp

`

**Comment by jaimecasero** [comment]
There are different players here SipStandardContext,SipStandardService, and SipConnectorService (per connector tag).

SipStandardContext is started when JBoss scans deployments dir as per jboss.web subssystem.
SipStandardService is started when jboss reads the sip subsystem in standalone.xml. It creates and start the SipApplicationDispather that provides outboundInts through SipNetworkManager.
SipConnectorService is started per Connector tag inside the sip subsystem. Its only started after SipStandardService start completed...

The SipConnectorService is the one that actually adds the connector to the SipNetworkManager, so SIPAppDispatcher is aware.

Both SipStandardContext and SipStandardService  are started in parallel by JBoss,since they are different subsystems (sip and web).

Ideally SipStandardContext  should only be started when SipStandardService and all SipConnectorService instances has been started.

Module dependencies are defined as:
sip->web->javax/dar/libs

**Comment by jaimecasero** [comment]
sipsubsystemparser.readelement
sipextension.initialize
sipsubssystemadd.populatemodel
sipconnectoradd.populatemodelX
sipsubssysmteadd.performBoot
->newControllers.addService
	---parallel->SipServerService.start
	
SipConnectorAdd.performRuntimeX

SipConnectorService.startX (afterSipServerService.start completition)
SipWarDeploymentProcessor.deploy

**Comment by jaimecasero** [comment]
https://code.google.com/archive/p/sipservlets/issues/277
