### ISSUE TITLE
Notify LB to add node only when RC is properly started 

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/sip-servlets#196]
sip-servlet should notify LB, only when everything is started, to add the node.
otherwise in some cases sip traffic starts coming and some RC classes were not initialised properly, which causes problems

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/196/create?referer=github" target="_blank">Log Time</a>

**Comment by maria-farooq** [comment]
https://app.box.com/s/gn7xtrj537gss9cg123a9f4khwg0mvs4

**Comment by deruelle** [comment]
@knosach please investigate this to add to JAIN SIP HA the ability for the application to specify when to start pinging the LB

**Comment by leftyb** [comment]
@jaimecasero As @deruelle commented, we can start testing on staging server for that issue when you can.

**Comment by jaimecasero** [comment]
the heartbeat pinging to LB its more a container issue. Whether SipServlets apps are started/deployed or not, seems more an App issue. The container is ready to handle the request, its just the SipServlet App is still not ready...

Having said that, I reckon we need to tackle this somehow, but lets not consider this a SIPServlets container issue per se. We may fix this in different levels, lets think about the most sensible place to solve it. Maybe we should advertise an status state along with the heartbeat ( this is usual stuff, i remember CSTA status..) so LB receives heartbeat, but the status still prevents the traffic sent...

**Comment by deruelle** [comment]
tying this to https://docs.google.com/document/d/116I4hbPZdYZpqZwdvoMq9MTfABQkZwfkXXW7D0RXMvE/edit

**Comment by deruelle** [comment]
@jaimecasero even if not a SIP Servlets issue per say. We need to solve it indeed as it creates graceful upgrades issues where the container receives some traffic before the application is deployed and ready to accept traffic. 
Until we can implement a full blown solution, a quick workaround could be for the SIP Servlets container to notify the LB to add himself only after https://github.com/RestComm/sip-servlets/blob/27fcd540f28baba45ead33f05ebafafd7afae9c4/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/SipApplicationDispatcherImpl.java#L483 or https://github.com/RestComm/sip-servlets/blob/27fcd540f28baba45ead33f05ebafafd7afae9c4/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/SipApplicationDispatcherImpl.java#L581 ?

**Comment by jaimecasero** [comment]
update doc
