### ISSUE TITLE
Make RC aware that a Graceful Shutdown has been triggered.- [ ]

### ISSUE THREAD

**Issue by leftyb** [RestComm/sip-servlets#251]
We need RC to be able to constantly query the DB and check if that node is the Master for any active conference before stopping.  If yes signal RC/Sip-Servlets that GS must be postponed by rescheduling the GS timer. RC needs to continue checking until no Master conference that belong to that node is still running.

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/251/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
does a propietary extension listener would work there for RC to receive the notification from sipservlets contaienr,instead of constanly polling the DB?

**Comment by leftyb** [comment]
@jaimecasero We need RC to query the DB for the state of the Master conferences that belong to that node. Not sure how your suggestion will help on that. I am missing something?

**Comment by deruelle** [comment]
@jaimecasero yes that would work. What the application does is irrelevant to the container. I think something similar to the extension of SipApplicationSession Lifetime where the application can instruct the container to extend the graceful shutdown for X minutes even if there is no more active sessions and after X minutes be notified again so it can extend Y times potentially until the Application can close everything properly.

**Comment by jaimecasero** [comment]
- [ ]
