### ISSUE TITLE
DataGrid Integration

### ISSUE THREAD

**Issue by desipepova** [RestComm/sip-servlets#27]
Original issue URL from Google Code:

https://code.google.com/p/sipservlets/issues/detail?id=67&colspec=ID%20Status%20MSS%20Summary

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/27/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
Posted on Apr 10, 2012 by Massive Wombat
Integrate with Infinispan and Cassandra like technologies See http://code.google.com/p/mobicents/issues/detail?id=2135

Comment #1

Posted on Aug 16, 2012 by Massive Wombat
(No comment was entered for this change.)

Comment #2

Posted on Jul 5, 2013 by Massive Wombat
(No comment was entered for this change.)

Comment #3

Posted on Dec 18, 2014 by Happy Rhino
Issue was moved to GitHub:

https://github.com/Mobicents/sip-servlets/issues/27

Comment #4

Posted on Dec 18, 2014 by Massive Wombat
(No comment was entered for this change.)

**Comment by jaimecasero** [comment]
same as https://github.com/RestComm/sip-servlets/issues/122 . closing
