### ISSUE TITLE
configure tomcat from base

### ISSUE THREAD

**Issue by sadeghpro** [RestComm/sip-servlets#338]
hi 
I want to configure tomcat from base. I download last tomcat from its site and replace  server.xml with server.xml of [this project](https://mobicents.ci.cloudbees.com/job/RestcommSipServlets-4.X-Release/lastSuccessfulBuild/artifact/) and insert this jars to tomcat lib directory
```

activation-1.1.1.jar
commons-codec-1.5.jar
commons-logging-1.0.4.jar
dnsjava-2.1.7.jar
gson-2.6.2.jar
httpclient-4.5.2.jar
httpcore-4.4.4.jar
jain-sip-api-1.2.0.jar
jain-sip-ri-1.2.307.jar
log4j-1.2.17.jar
log4j.xml
mail-1.4.jar
metrics-core-3.1.0.jar
restcomm-jain-sip-ext-1.3.24.jar
restcomm-jain-sip-ha-core-1.5.43.jar
restcomm-statistics-2.0.147.jar
sip-balancer-jar-2.0.41.jar
sip-servlets-annotations-4.0.122.jar
sip-servlets-application-router-4.0.122.jar
sip-servlets-catalina-8-4.0.122.jar
sip-servlets-client-4.0.122.jar
sip-servlets-core-api-4.0.122.jar
sip-servlets-impl-4.0.122.jar
sip-servlets-jruby-4.0.122.jar
sip-servlets-spec-4.0.122.jar
sip-servlets-tomcat-8-4.0.122.jar
slf4j-api-1.5.5.jar
slf4j-simple-1.5.5.jar
stun4j-1.0.MOBICENTS.jar

```
and also add this file to tomcat conf directory
```
dars/mobicents-dar.properties
mss-sip-stack.properties
```
I do this only from compare main tomcat vs tomcat from [here](https://mobicents.ci.cloudbees.com/job/RestcommSipServlets-4.X-Release/lastSuccessfulBuild/artifact/) 

but when run tomcat WebSocketB2BUASipServlet.java init function don't call and if I register tomcat log receive registeration and back a 500 error to the client

can any one fully explain how to config tomcat for sip container
tnx a lot 

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/338/create?referer=github" target="_blank">Log Time</a>

**Comment by sadeghpro** [comment]
or any one can fully explain config jboss eap from base
I want this to fully understand sip servlet 

Thank you way much

**Comment by zhouyusunquan** [comment]
i want to download  mss-1.6.0.FINAL-apache-tomcat-6.0.32

**Comment by gsaslis** [comment]
@sadeghpro did you ever manage to work around this? 
Did you follow the [Tomcat Getting Started Guide](http://documentation.telestax.com/core/sip_servlets/SIP_Servlets_Server_User_Guide.html#_getting_started_with_mss_tomcat_as7) in the docs ?

@zhouyusunquan are you facing a similar issue with @sadeghpro ? it is not clear to me from your comment what you are trying to achieve. would you mind elaborating please?
