### ISSUE TITLE
All download link not available ... 

### ISSUE THREAD

**Issue by hqtc123** [RestComm/sip-servlets#348]
The download links below  are all 404 ...

https://github.com/RestComm/sip-servlets/releases/download/v2.1.547/mss-2.1.547-apache-tomcat-7.0.50.zip

https://mobicents.ci.cloudbees.com/job/RestcommSipServlets-4.X-Release/lastSuccessfulBuild/artifact/

and  the link in doc  "  Getting Started with Restcomm SIP Servlets for Tomcat 7"
https://code.google.com/archive/p/sipservlets/wikis/Downloads.wiki

so , what do i need to make the sip-servlets work with tomcat 7 ?

**Comment by gsaslis** [comment]
Hi @hqtc123 ! 

Thanks for reporting this. We're going through a phase of some internal changes in infra, so we're experiencing some breakage here and there. Please do help us out by reporting any other links, etc. you find missing! 

@jaimecasero has just published a new binary under the https://github.com/RestComm/sip-servlets/releases - hope that helps in the meantime!

**Comment by hqtc123** [comment]
OK, 3ks for your work ~  @gsaslis
