### ISSUE TITLE
 I need more Detail information about the commercial License

### ISSUE THREAD

**Issue by hqtc123** [RestComm/sip-servlets#355]
OK
There is 
"Alternatively a commercial license can be obtained from Telestax (contact form)"  in the read me page , 
And I fill the form on [ http://go.telestax.com/general-inquiries]( http://go.telestax.com/general-inquiries)

 So , When can I receive the response?

**Comment by gsaslis** [comment]
@hqtc123 please drop me a private email to yorgos.saslis@telestax.com including your full name and company info, so I can pass this directly onto our sales team and have someone contact you asap!

In the meantime, I am closing this, so we can continue over email.
