### ISSUE TITLE
http://dev.telestax.com/sipservlets/   

### ISSUE THREAD

**Issue by hqtc123** [RestComm/sip-servlets#356]
Bad gateway ~

https://telestax.com/blog/mobicents-sip-servlets-2-0-0-final-with-support-for-html5-webrtc-is-out/　

Cannot download~

**Comment by gsaslis** [comment]
Hello @hqtc123 !

That's a pretty old article, dating back to 2012, so it looks like there's some broken links there. 

Please feel free to download the latest SIP Servlets binaries from the [Downloads section in the Restcomm site](https://www.restcomm.com/downloads/). 

I will close this issue - please feel free to reopen if you still can't get to the binary, or you are looking for something else.
