### ISSUE TITLE
[Tomcat7] Webapp path customization documentation

### ISSUE THREAD

**Issue by joafalves** [RestComm/sip-servlets#360]
Hello,

Is there any way to configure the root HTTP path to a specific deployed web app? I'm unable to find it on the documentation.

I have an application under /webapps/myApp which I want to assign as the root path directory. Is it possible? (Right now I must add the "myApp" on the url path)

Connector:
`<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443"/>`

Thanks.

**Comment by gsaslis** [comment]
Hi @joafalves, 

Unless I'm missing something, this sounds like a generic tomcat issue, and not a SIP Servlets one. 
The usual approach is to just name your WAR: "ROOT.war" 

Take a look e.g. here for more details: http://www.baeldung.com/tomcat-root-application

I'll be closing this - plz feel free to reopen if I've missed sth. 

Good luck! ;)
