### ISSUE TITLE
B2buaHelper.createResponseToOriginalRequest() does not set different To tag to created response.

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#4]
https://code.google.com/p/mobicents/issues/detail?id=2354

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/4/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
link died

**Comment by xhoaluu** [comment]
Closed
