### ISSUE TITLE
Have a new REGEX option in DAR for a specific header only

### ISSUE THREAD

**Issue by deruelle** [RestComm/sip-servlets#5]
https://code.google.com/p/mobicents/issues/detail?id=2357

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/5/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
I will add "HEADER_X" optional param, so we can match againts specific header values. First version will assume single-valued headers, although we should take into consideration multi-valued ones. The proposal includes dynamic header inspection, not predefined option names, so even propietary headers will be convered. This could be particularly interesting in some networks, where P-Headers are used to convey information coming from different networks (IN->IMS...)

**Comment by deruelle** [comment]
Sounds good to me. Just to be sure I have the correct picture in my mind, can you write what the DAR source would look like when you add HEADER_X ?

**Comment by jaimecasero** [comment]
ALL=("RestComm","DAR:From","NEUTRAL","","NO_ROUTE","0","DIRECTION=INBOUND HEADER_Via=.*2\.0.* HEADER_User-Agent=^TelScale")

In this  case, the msg will be routed if both Via contains 2.0 and user-agent startswith TelScale. Nevermind about the regex, its just  an example, so you can get the idea. The regex will be saved in the routeInfos, and evaluated only against header values, compared to current regex which compares against stringified sip request...

**Comment by deruelle** [comment]
just a minor thing, instead of a space they should probably be separated by commas or in separate Strings. what do you think ?

**Comment by jaimecasero** [comment]
I totally agree, and i thought the same the time i saw it. But the code that parses opetional params was already there. Since this logic parses a file out of the code, changing the "contract" could lead to integration problems during migration. I don't have any problem changing the separator to a more suitable char, but i was afraid of breaking something, so i was cautious there. What do you think? Should we take into consideration migration issues? I dont really know if there are so much deployments using some of these features (DIRECTION;REGEX...) that could be affected...

**Comment by deruelle** [comment]
Good thinking on migrations, I would say let's deprecate the space (we can completely remove it in the future) ie still provide support for it (but print a warning in the logs that it's deprecated) but also start supporting the params in separate Strings such as ALL=("RestComm","DAR:From","NEUTRAL","","NO_ROUTE","0","DIRECTION=INBOUND", "HEADER_Via=.2.0.", "HEADER_User-Agent=^TelScale")

**Comment by xhoaluu** [comment]
Closed

**Comment by jaimecasero** [comment]
@xhoaluu  which criteria you used to close this ticket?

**Comment by xhoaluu** [comment]
@jaimecasero 

I saw that there is some steps:
1/ in https://github.com/RestComm/sip-servlets/pull/64 : there is a commit "Added HeaderRegexCondition to implement issue#5"
2/ at the end of pull request:
"Thanks @jaimecasero. Now all is working. I merged it to master."
