### ISSUE TITLE
ACK is not sent to negative forked response

### ISSUE THREAD

**Issue by akozlovcodeminders** [RestComm/sip-servlets#78]
I'm using sip-servlets 3.0.564.

Scenario with forking:
1. Application sends INVITE to client
2. The first client returns 180
3. The second client returns 180
4. The first client returns 200 OK
5. The second client returns 486
Result:
Sip Container does not sends ACK to 486 response (see logs in attachment)

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/78/create?referer=github" target="_blank">Log Time</a>

**Comment by akozlovcodeminders** [comment]
Sorry, I have logs, but does not understand how to attach

**Comment by jaimecasero** [comment]
There is a similar existing testcase at https://github.com/RestComm/sip-servlets/blob/master/sip-servlets-test-suite/testsuite/src/test/java/org/mobicents/servlet/sip/testsuite/proxy/ProxyBestResponseTest.java

Clone the testcase, and modify it accordingly to reproduce scenario, and confirm issue/bug.

**Comment by deruelle** [comment]
@akozlovcodeminders the test contributed by @chaitanya87 at https://github.com/RestComm/sip-servlets/pull/113 shows that the container on the latest master code is handling this correctly. Please upgrade. Marking as Closed and Invalid
